In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("../Data/data_2019.csv")

In [3]:
df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
0,En construcción,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,319m²,NaN,NaN,NaN,Casa en Venta en Estancias del Rio
1,En construcción,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,410m²,NaN,NaN,NaN,Isla Mocoli Urb. Pacifica - 4 Dorm.
2,NaN,1,1,3,//maps.google.com/maps/api/staticmap?center=-2...,83m²,NaN,NaN,NaN,Vendo Casa de Estreno Urbanizacion Villa Itali...
3,5,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,186m²,NaN,NaN,NaN,Hermosa Casa en Venta Urb. Arcadia - 3 Dorm. 2...
4,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,NaN,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
...,...,...,...,...,...,...,...,...,...,...
10277,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
10278,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10279,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10280,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10281,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [4]:
df.shape

(10282, 10)

In [5]:
df.head(10)

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
0,En construcción,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,319m²,NaN,NaN,NaN,Casa en Venta en Estancias del Rio
1,En construcción,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,410m²,NaN,NaN,NaN,Isla Mocoli Urb. Pacifica - 4 Dorm.
2,NaN,1,1,3,//maps.google.com/maps/api/staticmap?center=-2...,83m²,NaN,NaN,NaN,Vendo Casa de Estreno Urbanizacion Villa Itali...
3,5,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,186m²,NaN,NaN,NaN,Hermosa Casa en Venta Urb. Arcadia - 3 Dorm. 2...
4,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,NaN,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
5,13,7,7,10,//maps.google.com/maps/api/staticmap?center=-2...,1460m²,NaN,NaN,NaN,Espectacular Mansión en Urbanización Aquamarin...
6,NaN,NaN,NaN,NaN,//maps.google.com/maps/api/staticmap?center=-2...,NaN,NaN,NaN,NaN,NaN
7,4,3,4,3,//maps.google.com/maps/api/staticmap?center=-2...,200m²,NaN,NaN,NaN,Punta Esmeralda - Casa en Venta 3d - $
8,4,3,2,0,//maps.google.com/maps/api/staticmap?center=-2...,144m²,NaN,NaN,NaN,"Casa en Venta en Villa Club, Esquinera $99.000"
9,NaN,0,4,14,//maps.google.com/maps/api/staticmap?center=-2...,767m²,NaN,NaN,NaN,Casa - Samborondón

In [6]:
df.tail(10)

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
10272,10,4,4,2,//maps.google.com/maps/api/staticmap?center=-2...,400m²,USD 480.000,NaN,NaN,Casa de Venta en Samborondon
10273,5,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,250m²,USD 270.000,NaN,NaN,Vendo Linda Casa en Los Primeros Kms de Sambor...
10274,4,3,2,1,//maps.google.com/maps/api/staticmap?center=-2...,136m²,USD 120.000,NaN,NaN,"Venta Casa en Urb. Villa Club, etapa Jupiter, ..."
10275,25,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,560m²,USD 220.000,NaN,NaN,Vendo Propiedad de Oportunidad en Urdesa Norte
10276,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Moderno Proyecto en La Peninsula Al Lago 4 Dorm
10277,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
10278,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10279,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10280,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10281,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [7]:
df.dtypes

antigüedad                object
cuartos                   object
cuartosdebaño             object
estacionamiento           object
latlong                   object
metroscuadradostotales    object
precio                    object
publicado                 object
tipodevendedor            object
titulo                    object
dtype: object

In [8]:
df["cuartos"]

0        3
1        4
2        1
3        3
4        4
        ..
10277    4
10278    5
10279    3
10280    1
10281    4
Name: cuartos, Length: 10282, dtype: object

In [9]:
df["cuartos"].value_counts() #cuenta cuantas veces ese valor se repite

3             4001
4             3450
0              746
5              745
2              320
1              295
6              277
7              111
8               69
9               43
10              42
12              22
A estrenar      14
11              10
13               4
18               4
33               2
19               2
31               2
45               2
14               2
15               2
20               1
cuartos          1
Name: cuartos, dtype: int64

In [10]:
df["cuartos"].unique() #me da los diferentes valores unicos como un vector.

array(['3', '4', '1', '7', nan, '0', '5', '6', '10', '2', '9', '8', '13',
       'A estrenar', '11', '33', '12', '19', '18', '31', '45', '14', '20',
       '15', 'cuartos'], dtype=object)

In [11]:
df["cuartos"].nunique() #me da la cantidad de valores unicos que hay

24

In [12]:
df.loc[3:10,["cuartos","antigüedad"]] #permite seleccionar los indices de las filas que quiero mostrar y las columnas df.loc[filas,[columna1, column2.. , ....]]

   cuartos antigüedad
3        3          5
4        4          5
5        7         13
6      NaN        NaN
7        3          4
8        3          4
9        0        NaN
10       3          6

In [13]:
df.loc[:,:] #si pongo dos puntos isgnifica que tomo todas las filas y columnas.

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
0,En construcción,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,319m²,NaN,NaN,NaN,Casa en Venta en Estancias del Rio
1,En construcción,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,410m²,NaN,NaN,NaN,Isla Mocoli Urb. Pacifica - 4 Dorm.
2,NaN,1,1,3,//maps.google.com/maps/api/staticmap?center=-2...,83m²,NaN,NaN,NaN,Vendo Casa de Estreno Urbanizacion Villa Itali...
3,5,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,186m²,NaN,NaN,NaN,Hermosa Casa en Venta Urb. Arcadia - 3 Dorm. 2...
4,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,NaN,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
...,...,...,...,...,...,...,...,...,...,...
10277,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
10278,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10279,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10280,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10281,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [14]:
serieboleana = df["cuartosdebaño"]== "cuartosdebaño" #comparo para la columna cuartosdebaño los valores que sean "cuartosdebaño"

In [15]:
df.loc[serieboleana,:] #utilizo la serie obtenida para ver cual es la observacion que tiene la palabra cuarrto de baño como valor de la columna "cuartosdebaño"

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
5130,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo

In [16]:
serieboleana2 = df["cuartosdebaño"]!= "cuartosdebaño" #comparo para la columna cuartosdebaño los valores que sean diferentes de cuartosdebaño

In [17]:
df= df.loc[serieboleana2,:] #necesito guardarlo en una variable, generalmente se usa la misma para sobreescribirlo y no usar memoria extra.

In [18]:
df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
0,En construcción,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,319m²,NaN,NaN,NaN,Casa en Venta en Estancias del Rio
1,En construcción,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,410m²,NaN,NaN,NaN,Isla Mocoli Urb. Pacifica - 4 Dorm.
2,NaN,1,1,3,//maps.google.com/maps/api/staticmap?center=-2...,83m²,NaN,NaN,NaN,Vendo Casa de Estreno Urbanizacion Villa Itali...
3,5,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,186m²,NaN,NaN,NaN,Hermosa Casa en Venta Urb. Arcadia - 3 Dorm. 2...
4,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,NaN,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
...,...,...,...,...,...,...,...,...,...,...
10277,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
10278,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10279,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10280,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10281,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [19]:
df.tail() #muestro los ultimos 5 valores, y podemos ver que los indices no se regeneran

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
10277,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
10278,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10279,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10280,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10281,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [20]:
df.reset_index(drop=True,inplace=True) #Regenera los indices, el argumento drop=True, elimina la oclumna con los indices originales
#El argumento implace=True, hace que modifique el dataframe sobresimismo y no necesito guardarlo en una nueva variable

In [21]:
df.tail() #Podemos ver que como eliminamos una fila, y reslisamos reste_index(), tenemos una fila menos

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
10276,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
10277,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10278,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10279,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10280,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [22]:
 df["cuartosdebaño"].unique()

array(['3', '4', '1', '7', nan, '2', '5', '6', '11', '0', '9', '8', '10',
       '19', '15', '12', '13', '14', '16', '18'], dtype=object)

In [23]:
#Trabajando con valores Nulos

In [24]:
df["cuartosdebaño"].isnull() #Devuelve valores que son nulas

0        False
1        False
2        False
3        False
4        False
         ...
10276    False
10277    False
10278    False
10279    False
10280    False
Name: cuartosdebaño, Length: 10281, dtype: bool

In [25]:
df["cuartosdebaño"].notnull() #Devuelve valores que no son nulas

0        True
1        True
2        True
3        True
4        True
         ...
10276    True
10277    True
10278    True
10279    True
10280    True
Name: cuartosdebaño, Length: 10281, dtype: bool

In [26]:
df= df.loc[df["cuartosdebaño"].notnull(),:]

In [27]:
df.shape

(10249, 10)

In [28]:
#df.loc[(df["antigüedad"].notnull())&(df["cuartos"].notnull())&(df["cuartosdebaño"].notnull()),:] #Buscar las que no sean nulas en ninguna de estas columnas

In [29]:
df.dropna(subset=["antigüedad","cuartos","cuartosdebaño","metroscuadradostotales","latlong","precio"],inplace= True) #me da las observaciones que no tengan nulo en las columnas dadas como argumentos

C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\338958025.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=["antigüedad","cuartos","cuartosdebaño","metroscuadradostotales","latlong","precio"],inplace= True) #me da las observaciones que no tengan nulo en las columnas dadas como argumentos

In [30]:
df.shape

(4706, 10)

In [31]:
df["metroscuadradostotales"] = df["metroscuadradostotales"].str.replace("m²","").astype(int) #reemplazo los valores m2 por el vacio y transformo en tipo de dato entero, luego reemplazo esa columna por la original

C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\1981155309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["metroscuadradostotales"] = df["metroscuadradostotales"].str.replace("m²","").astype(int) #reemplazo los valores m2 por el vacio y transformo en tipo de dato entero, luego reemplazo esa columna por la original

In [32]:
df.head()

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
5130,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480,USD 565.000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
5131,A estrenar,4,3,2,//maps.google.com/maps/api/staticmap?center=-2...,400,USD 370.000,NaN,NaN,Vendo Casa Moderna de Estreno en Isla Mocoli
5132,20,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,244,USD 140.000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...
5133,En construcción,0,4,2,//maps.google.com/maps/api/staticmap?center=-2...,1,USD 259.000,NaN,NaN,Se Vende Proyecto en Isla Celeste Reserva Solo...
5134,A estrenar,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,245,USD 245.000,NaN,NaN,Isla Celeste 243 m² Const y 225 m² Terreno Her...

In [33]:
df.dtypes

antigüedad                object
cuartos                   object
cuartosdebaño             object
estacionamiento           object
latlong                   object
metroscuadradostotales     int32
precio                    object
publicado                 object
tipodevendedor            object
titulo                    object
dtype: object

In [34]:
df= df.loc[df["precio"]!="Consultar precio",:]

In [35]:
df["precio"] = df["precio"].str.replace("USD ","",).str.replace(".","",regex= False).astype(int) #con rgeex= False, hago que tome en cuenta el punto

In [36]:
palabras= ["A estrenar", "En construcción"]

In [37]:
df= df.loc[~df["antigüedad"].isin(palabras),:] #evalua si cada valor de la coleccion esta dentro de la fila antiguedad, como quiero los que no tenga, niego la serie booleana con el simbolo de la ñ

In [38]:
df["antigüedad"] = df["antigüedad"].astype(float)

In [39]:
df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
5130,5.0,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480,565000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
5132,20.0,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,244,140000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...
5136,10.0,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,580,425000,NaN,NaN,Samborondon Km 4 - Urb San Isidro - Casa 3 Dor...
5138,14.0,4,5,2,//maps.google.com/maps/api/staticmap?center=-2...,240,280000,NaN,NaN,Vendo Casa Portón de Lomas Urdesa (Costabienes)
5139,30.0,3,2,1,//maps.google.com/maps/api/staticmap?center=-2...,170,175000,NaN,NaN,"Venta de Casa, Vía a Samborondon Km 1 Planta Baja"
...,...,...,...,...,...,...,...,...,...,...
10274,25.0,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,560,220000,NaN,NaN,Vendo Propiedad de Oportunidad en Urdesa Norte
10277,4.0,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700,790000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10278,6.0,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350,380000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10279,1.0,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256,220000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10280,14.0,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230,285000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [40]:
df["precio"]/df["metroscuadradostotales"]

5130     1177.083333
5132      573.770492
5136      732.758621
5138     1166.666667
5139     1029.411765
            ...
10274     392.857143
10277    1128.571429
10278    1085.714286
10279     859.375000
10280    1239.130435
Length: 3550, dtype: float64

In [41]:
df.shape

(3550, 10)

In [42]:
df["precio*m2"] = df["precio"] / df["metroscuadradostotales"] #creo una nueva columna

In [43]:
df.reset_index(drop=True, inplace=True)

In [44]:
df.head()

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo,precio*m2
0,5.0,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480,565000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal,1177.083333
1,20.0,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,244,140000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...,573.770492
2,10.0,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,580,425000,NaN,NaN,Samborondon Km 4 - Urb San Isidro - Casa 3 Dor...,732.758621
3,14.0,4,5,2,//maps.google.com/maps/api/staticmap?center=-2...,240,280000,NaN,NaN,Vendo Casa Portón de Lomas Urdesa (Costabienes),1166.666667
4,30.0,3,2,1,//maps.google.com/maps/api/staticmap?center=-2...,170,175000,NaN,NaN,"Venta de Casa, Vía a Samborondon Km 1 Planta Baja",1029.411765

In [45]:
df["latlong"]

0       //maps.google.com/maps/api/staticmap?center=-2...
1       //maps.google.com/maps/api/staticmap?center=-2...
2       //maps.google.com/maps/api/staticmap?center=-2...
3       //maps.google.com/maps/api/staticmap?center=-2...
4       //maps.google.com/maps/api/staticmap?center=-2...
                              ...
3545    //maps.google.com/maps/api/staticmap?center=-2...
3546    //maps.google.com/maps/api/staticmap?center=nu...
3547    //maps.google.com/maps/api/staticmap?center=-2...
3548    //maps.google.com/maps/api/staticmap?center=nu...
3549    //maps.google.com/maps/api/staticmap?center=nu...
Name: latlong, Length: 3550, dtype: object

In [46]:
df["latlong"].str.split("=", n=1, expand=True)[1] #Con n tomo solamente hasta el indice que me interesa de la lista creada con split. y con expand=True hago que lo que devuelve sea un dataframe, adicional al final con [1] tomo solamente la columna de los valores de lat y long

0       -2.115345389952465,-79.85616255437014&zoom=16&...
1       -2.230328339537673,-79.90216345507815&zoom=16&...
2       -2.1190084,-79.86893909999998&zoom=16&markers=...
3       -2.1590432,-79.90947510000001&zoom=16&markers=...
4       -2.1447394,-79.8644152&zoom=16&markers=-2.1447...
                              ...
3545    -2.1561673,-79.90530819999998&zoom=16&channel=...
3546    null,null&zoom=16&channel=PV&size=780x456&sens...
3547    -2.19522897016541,-80.05308412611731&zoom=16&m...
3548    null,null&zoom=16&channel=PV&size=780x456&sens...
3549    null,null&zoom=16&channel=PV&size=780x456&sens...
Name: 1, Length: 3550, dtype: object

In [47]:
df["latlong"].str.split("=", n=1, expand=True)[1].str.split("&", expand=True)

,0,1,2,3,4,5,6,7,8
0,"-2.115345389952465,-79.85616255437014",zoom=16,"markers=-2.115345389952465,-79.85616255437014",channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=yodWqt7SOdUVK2FNJ7YqJoJVgSw=
1,"-2.230328339537673,-79.90216345507815",zoom=16,"markers=-2.230328339537673,-79.90216345507815",channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=dtgLW4IUAzFxq4NvMWDwuTQMKT4=
2,"-2.1190084,-79.86893909999998",zoom=16,"markers=-2.1190084,-79.86893909999998",channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=7TS6OUsux543A5sPlV38YGnAk5I=
3,"-2.1590432,-79.90947510000001",zoom=16,"markers=-2.1590432,-79.90947510000001",channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=mP2fCqVS1s-u7QvPDH-upAVTLuU=
4,"-2.1447394,-79.8644152",zoom=16,"markers=-2.1447394,-79.8644152",channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=XKRdD-fq-dzaxfvoX-3j4bGCoZQ=
...,...,...,...,...,...,...,...,...,...
3545,"-2.1561673,-79.90530819999998",zoom=16,channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=Z2LzDhQQlhMkf3GFEV3OTVJyDAU=,None
3546,"null,null",zoom=16,channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=plBqptuEZa5UtzUMjC7xLIb4yiE=,None
3547,"-2.19522897016541,-80.05308412611731",zoom=16,"markers=-2.19522897016541,-80.05308412611731",channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=D7dg6G2fAApX0fnLesIEVBW7oCk=
3548,"null,null",zoom=16,channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=plBqptuEZa5UtzUMjC7xLIb4yiE=,None
3549,"null,null",zoom=16,channel=PV,size=780x456,sensor=true,scale=2,key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w,signature=plBqptuEZa5UtzUMjC7xLIb4yiE=,None

In [48]:
df["latlong"].str.split("=", n=1, expand=True)[1].str.split("&", expand=True)[0]

0       -2.115345389952465,-79.85616255437014
1       -2.230328339537673,-79.90216345507815
2               -2.1190084,-79.86893909999998
3               -2.1590432,-79.90947510000001
4                      -2.1447394,-79.8644152
                        ...
3545            -2.1561673,-79.90530819999998
3546                                null,null
3547     -2.19522897016541,-80.05308412611731
3548                                null,null
3549                                null,null
Name: 0, Length: 3550, dtype: object

In [49]:
df["latlong"].str.split("=", n=1, expand=True)[1].str.split("&", expand=True)[0].str.split(",", expand=True)

                       0                   1
0     -2.115345389952465  -79.85616255437014
1     -2.230328339537673  -79.90216345507815
2             -2.1190084  -79.86893909999998
3             -2.1590432  -79.90947510000001
4             -2.1447394         -79.8644152
...                  ...                 ...
3545          -2.1561673  -79.90530819999998
3546                null                null
3547   -2.19522897016541  -80.05308412611731
3548                null                null
3549                null                null

[3550 rows x 2 columns]

In [50]:
df[["lat","long"]] = df["latlong"].str.split("=", n=1, expand=True)[1].str.split("&", expand=True)[0].str.split(",", expand=True)

In [51]:
df.dtypes

antigüedad                float64
cuartos                    object
cuartosdebaño              object
estacionamiento            object
latlong                    object
metroscuadradostotales      int32
precio                      int32
publicado                  object
tipodevendedor             object
titulo                     object
precio*m2                 float64
lat                        object
long                       object
dtype: object

In [52]:
df= df.loc[(df["lat"]!="null")&(df["long"]!="null"),:]

In [53]:
df["lat"]=df["lat"].astype(float)
df["long"]=df["long"].astype(float)

C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\278073752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["lat"]=df["lat"].astype(float)
C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\278073752.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["long"]=df["long"].astype(float)

In [54]:
df.shape

(2900, 13)

In [55]:
df.reset_index(drop=True, inplace=True)

In [56]:
df.head()

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo,precio*m2,lat,long
0,5.0,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480,565000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal,1177.083333,-2.115345,-79.856163
1,20.0,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,244,140000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...,573.770492,-2.230328,-79.902163
2,10.0,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,580,425000,NaN,NaN,Samborondon Km 4 - Urb San Isidro - Casa 3 Dor...,732.758621,-2.119008,-79.868939
3,14.0,4,5,2,//maps.google.com/maps/api/staticmap?center=-2...,240,280000,NaN,NaN,Vendo Casa Portón de Lomas Urdesa (Costabienes),1166.666667,-2.159043,-79.909475
4,30.0,3,2,1,//maps.google.com/maps/api/staticmap?center=-2...,170,175000,NaN,NaN,"Venta de Casa, Vía a Samborondon Km 1 Planta Baja",1029.411765,-2.144739,-79.864415

In [57]:
df.shape

(2900, 13)

In [58]:
df.drop(columns=["latlong","publicado","tipodevendedor"],inplace= True) #Drop elimina columnas, le paso como lista las columnas que quiero eliminar, e implace para que lo haga sobre el mismo dataframe / en este caso elimine las columnas que no tienen informacion de valor

C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\2093226500.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["latlong","publicado","tipodevendedor"],inplace= True) #Drop elimina columnas, le paso como lista las columnas que quiero eliminar, e implace para que lo haga sobre el mismo dataframe / en este caso elimine las columnas que no tienen informacion de valor

In [59]:
df.shape

(2900, 10)

In [60]:
df.head()

,antigüedad,cuartos,cuartosdebaño,estacionamiento,metroscuadradostotales,precio,titulo,precio*m2,lat,long
0,5.0,4,4,0,480,565000,Arrecife - Punta Mocoli Design By Jannina Cabal,1177.083333,-2.115345,-79.856163
1,20.0,4,4,3,244,140000,Venta de Casa Cdla. del Biess Remodelada - Sec...,573.770492,-2.230328,-79.902163
2,10.0,3,3,2,580,425000,Samborondon Km 4 - Urb San Isidro - Casa 3 Dor...,732.758621,-2.119008,-79.868939
3,14.0,4,5,2,240,280000,Vendo Casa Portón de Lomas Urdesa (Costabienes),1166.666667,-2.159043,-79.909475
4,30.0,3,2,1,170,175000,"Venta de Casa, Vía a Samborondon Km 1 Planta Baja",1029.411765,-2.144739,-79.864415

In [61]:
df.loc[df["titulo"].str.lower().str.contains("samborondon|samborondón|sambo |sanborondon"),:] #uso contains para ver si contiene o no esa cadena de caracteres, puedo agregar mas de una palabra con el or

,antigüedad,cuartos,cuartosdebaño,estacionamiento,metroscuadradostotales,precio,titulo,precio*m2,lat,long
2,10.0,3,3,2,580,425000,Samborondon Km 4 - Urb San Isidro - Casa 3 Dor...,732.758621,-2.119008,-79.868939
4,30.0,3,2,1,170,175000,"Venta de Casa, Vía a Samborondon Km 1 Planta Baja",1029.411765,-2.144739,-79.864415
10,8.0,5,7,1,2000,950000,Urb Camino Real Casa Tipo Mansión Km 2 Vía a S...,475.000000,-2.136868,-79.863641
16,4.0,3,4,1,175,182000,Casa en Venta en Exclusiva Urbanización Bali/ ...,1040.000000,-2.051632,-79.902433
20,13.0,7,7,10,1460,575000,Espectacular Mansión en Urbanización Aquamarin...,393.835616,-2.152074,-79.862583
...,...,...,...,...,...,...,...,...,...,...
2851,12.0,3,4,2,250,320000,Casa de Venta en Via Samborondon,1280.000000,-2.137653,-79.863682
2852,8.0,4,4,3,300,315000,"*vendo Moderna Casa en Urb Fontana, Samborondon",1050.000000,-2.130212,-79.870964
2881,8.0,3,2,2,180,107000,Vendo Casa en Samborondon. Urb. Fuentes del Ri...,594.444444,-2.058171,-79.870634
2895,10.0,4,4,2,400,480000,Casa de Venta en Samborondon,1200.000000,-2.271652,-78.999308
2896,5.0,3,3,2,250,270000,Vendo Linda Casa en Los Primeros Kms de Sambor...,1080.000000,-2.140583,-79.868761

In [69]:
df.shape

(2900, 10)

In [71]:
df.drop_duplicates(subset=["lat","long"],keep="last",inplace=True) #revisa si dos o mas observaciones tienen el mismo valor en lat y long, y el segundo argumento me dice cual observacion de las repetidas se mantiene

C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\386358315.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset=["lat","long"],keep="last",inplace=True) #revisa si dos o mas observaciones tienen el mismo valor en lat y long, y el segundo argumento me dice cual observacion de las repetidas se mantiene

In [72]:
df.shape

(1486, 10)

In [73]:
df.iloc[:2,:2] #iloc trabaja como loc pero en lugar de etiquetas utiliza indices

   antigüedad cuartos
0         5.0       4
1        20.0       4

In [74]:
df.loc[:2,"antigüedad":"cuartos"]

   antigüedad cuartos
0         5.0       4
1        20.0       4

In [ ]:
#uso de apply

In [76]:
def category(value): #primero creo la funcion que quiero hacer 
    if value > 120000:
        return "A"
    elif value > 60000:
        return "B"
    else:
        return "C"

In [78]:
df["category"]= df["precio"].apply(category)

C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\890795989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["category"]= df["precio"].apply(category)

In [79]:
df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,metroscuadradostotales,precio,titulo,precio*m2,lat,long,category
0,5.0,4,4,0,480,565000,Arrecife - Punta Mocoli Design By Jannina Cabal,1177.083333,-2.115345,-79.856163,A
1,20.0,4,4,3,244,140000,Venta de Casa Cdla. del Biess Remodelada - Sec...,573.770492,-2.230328,-79.902163,A
3,14.0,4,5,2,240,280000,Vendo Casa Portón de Lomas Urdesa (Costabienes),1166.666667,-2.159043,-79.909475,A
5,5.0,3,4,2,186,215000,Hermosa Casa en Venta Urb. Arcadia - 3 Dorm. 2...,1155.913978,-2.185845,-80.002310,A
7,40.0,4,3,2,600,320000,Casa en Venta. Una Sola Planta 275.72 m² de Co...,533.333333,-2.168559,-79.939266,A
...,...,...,...,...,...,...,...,...,...,...,...
2895,10.0,4,4,2,400,480000,Casa de Venta en Samborondon,1200.000000,-2.271652,-78.999308,A
2896,5.0,3,3,2,250,270000,Vendo Linda Casa en Los Primeros Kms de Sambor...,1080.000000,-2.140583,-79.868761,A
2897,4.0,3,2,1,136,120000,"Venta Casa en Urb. Villa Club, etapa Jupiter, ...",882.352941,-2.028782,-79.895465,B
2898,25.0,4,4,3,560,220000,Vendo Propiedad de Oportunidad en Urdesa Norte,392.857143,-2.156167,-79.905308,A
2899,6.0,3,4,2,350,380000,Oportunidad Moderna Casa en Via a La Costa Urb...,1085.714286,-2.195229,-80.053084,A

In [80]:
#uso de apply en dataframes

In [82]:
def calculoMetricas(row):
    pmt2= row["precio"]/row["metroscuadradostotales"]
    pmt22= row["precio"]*row["metroscuadradostotales"]
    return [pmt2,pmt22]

In [84]:
df[["a","b"]]= df.apply(calculoMetricas,axis=1,result_type="expand") #Con el result_type="expand", hago que me devuelva un dataframe y luego puedo conectarlas igualando a el dataframe original con los nuevos nombres de las filas dentro de una lista.

C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\1994355231.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["a","b"]]= df.apply(calculoMetricas,axis=1,result_type="expand") #Con el result_type="expand", hago que me devuelva un dataframe y luego puedo conectarlas igualando a el dataframe original con los nuevos nombres de las filas dentro de una lista.
C:\Users\CltControl.GGIECSOFWRK\AppData\Local\Temp\ipykernel_14524\1994355231.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["a","b"]]= df.apply(calculoMetricas,axis=1,result_type="expand") #Con el result_type="expand", hago que me devuelva un dataframe y luego puedo conectarlas igualando a el dataframe original con los nuevos nombres de las filas dentro de una lista.

In [87]:
df["metroscuadradostotales"].min()

7

In [86]:
df["precio"].min()

89

In [88]:
df.describe() #me da varias caracteristicas estadisticas generales del dataframe

,antigüedad,metroscuadradostotales,precio,precio*m2,lat,long,a,b
count,1486.000000,1486.000000,1.486000e+03,1486.000000,1486.000000,1486.000000,1486.000000,1.486000e+03
mean,12.660162,960.049798,3.164011e+05,856.034352,-2.100321,-79.910776,856.034352,6.914186e+08
std,10.400964,18480.771159,3.473385e+05,1568.677775,1.031694,0.450566,1568.677775,1.417473e+10
min,1.000000,7.000000,8.900000e+01,0.772059,-2.383959,-95.626071,0.772059,8.900000e+03
25%,5.000000,170.000000,1.200000e+05,578.947368,-2.174861,-79.923694,578.947368,2.160125e+07
50%,10.000000,275.000000,2.300000e+05,793.650794,-2.139015,-79.901704,793.650794,6.306000e+07
75%,19.000000,500.000000,3.800000e+05,1000.000000,-2.085637,-79.872089,1000.000000,1.902875e+08
max,80.000000,700000.000000,6.000000e+06,60000.000000,37.032729,-73.637690,60000.000000,5.250000e+11

In [89]:
df["precio"].sort_values() #ordena de menor a mayor
df["precio"].sort_values(ascending= False) #ordena de mayor a menor

1634         89
2429        105
2504       1500
2438       4000
697       17000
         ...
1692    2200000
2660    3000000
2673    3200000
2568    3500000
2686    6000000
Name: precio, Length: 1486, dtype: int32

In [91]:
df.sort_values(by=["precio"], ascending= False) #en esto caso veo el dataframe ordenado por la columna dada

,antigüedad,cuartos,cuartosdebaño,estacionamiento,metroscuadradostotales,precio,titulo,precio*m2,lat,long,category,a,b
2686,8.0,6,7,6,6000,6000000,Casa con Vista Al Lago Excelente Urbanización ...,1000.000000,-2.108551,-79.871913,A,1000.000000,3.600000e+10
2568,20.0,10,6,10,1797,3500000,Vendo Villa en Urdesa Av Cirncunvalacion Sur,1947.690595,-2.170194,-79.911687,A,1947.690595,6.289500e+09
2673,20.0,5,4,15,5239,3200000,Casa en Venta Circunvalacion Norte,610.803588,-2.175398,-79.904479,A,610.803588,1.676480e+10
2660,1.0,6,10,6,1798,3000000,"Vendo Casa de Lujo Vía Samborondon, Patio Ampl...",1668.520578,-2.142778,-79.861367,A,1668.520578,5.394000e+09
1692,5.0,5,7,5,1306,2200000,Via Samborondon Villa Inteligente de Estilo Mi...,1684.532925,-2.020023,-79.867061,A,1684.532925,2.873200e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,8.0,3,1,0,105,17000,"Casa en Venta de Oportunidad, Entrada de La 8",161.904762,-2.118396,-79.947512,C,161.904762,1.785000e+06
2438,3.0,3,3,1,500,4000,Alquilo Casa Amoblada con Vista Al Lago.,8.000000,-2.106387,-79.872496,C,8.000000,2.000000e+06
2504,18.0,3,3,1,350,1500,"Los Parques Rento Casa de Dos Pisos con 3 Hab,...",4.285714,-2.173192,-79.943753,C,4.285714,5.250000e+05
2429,9.0,3,2,1,136,105,Vendo Casa Esquinera en Villa Club,0.772059,-2.082692,-79.873195,C,0.772059,1.428000e+04
1634,2.0,3,2,1,100,89,"Vendo Casa en La Urbanización La Joya, Etapa C...",0.890000,-2.049584,-79.914692,C,0.890000,8.900000e+03

In [ ]:
df.to_csv("../output/data_2019clean.csv", index=False)